version: "3.1"
services:
  flask_python:
    build:
      context: .
      dockerfile: df.Dockerfile
    tty: true
    volumes:
      - ./shared:/shared
    ports:
      - 5000:5000
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
